name: Create manifest PR
on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main


jobs:
  call_workflow:
    uses: nordicbuilder/action-manifest-pr/auto-manifest-PR.yml@main
    secrets: inherit
