name: Create manifest PR
on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    branches:
      - main


jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: print debug
      run: |
        echo "GitHub Event - Pull Request: ${{ toJson(github.event.pull_request) }}"

  call_workflow:
    uses: karhama/sdk-nrf/.github/workflows/create-manifest-PR.yml@main
    with:
      repo-path: ${{ github.repository }}
      PR-number: ${{ github.event.pull_request.number }}
      trigger: 'opened'
    secrets: inherit
